# Generated by Django 5.2.6 on 2025-09-25 16:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('company_name', models.CharField(max_length=255, verbose_name='Company name')),
                ('license_number', models.CharField(blank=True, max_length=100, verbose_name='License number')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Is verified')),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentCommission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('commission_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Commission rate (%)')),
                ('order_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Order amount')),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Commission amount')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Currency')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved at')),
                ('rejected_at', models.DateTimeField(blank=True, null=True, verbose_name='Rejected at')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Rejection reason')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Paid at')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='Payment method')),
                ('payment_reference', models.CharField(blank=True, max_length=100, verbose_name='Payment reference')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Agent Commission',
                'verbose_name_plural': 'Agent Commissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentCustomer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Customer name')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Customer email')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Customer phone')),
                ('customer_address', models.TextField(blank=True, verbose_name='Customer address')),
                ('customer_city', models.CharField(blank=True, max_length=100, verbose_name='Customer city')),
                ('customer_country', models.CharField(blank=True, max_length=100, verbose_name='Customer country')),
                ('customer_birth_date', models.DateField(blank=True, null=True, verbose_name='Customer birth date')),
                ('customer_gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, verbose_name='Customer gender')),
                ('preferred_language', models.CharField(choices=[('fa', 'Persian'), ('en', 'English'), ('ar', 'Arabic')], default='fa', max_length=10, verbose_name='Preferred language')),
                ('preferred_contact_method', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS')], default='email', max_length=20, verbose_name='Preferred contact method')),
                ('customer_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked'), ('vip', 'VIP')], default='active', max_length=20, verbose_name='Customer status')),
                ('customer_tier', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='bronze', max_length=20, verbose_name='Customer tier')),
                ('relationship_notes', models.TextField(blank=True, verbose_name='Relationship notes')),
                ('special_requirements', models.TextField(blank=True, verbose_name='Special requirements')),
                ('marketing_consent', models.BooleanField(default=False, verbose_name='Marketing consent')),
                ('total_orders', models.PositiveIntegerField(default=0, verbose_name='Total orders')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total spent')),
                ('last_order_date', models.DateTimeField(blank=True, null=True, verbose_name='Last order date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created_by_agent', models.BooleanField(default=True, verbose_name='Created by agent')),
                ('requires_verification', models.BooleanField(default=True, verbose_name='Requires email verification')),
                ('credentials_sent', models.BooleanField(default=False, verbose_name='Login credentials sent')),
                ('credentials_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Credentials sent at')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='Last login at')),
                ('login_count', models.PositiveIntegerField(default=0, verbose_name='Login count')),
            ],
            options={
                'verbose_name': 'Agent Customer',
                'verbose_name_plural': 'Agent Customers',
            },
        ),
        migrations.CreateModel(
            name='AgentPricingRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('product_type', models.CharField(choices=[('tour', 'تور'), ('event', 'رویداد'), ('transfer', 'ترانسفر'), ('car_rental', 'اجاره ماشین')], max_length=20, verbose_name='نوع محصول')),
                ('pricing_method', models.CharField(choices=[('discount_percentage', 'تخفیف درصدی'), ('fixed_price', 'قیمت ثابت'), ('markup_percentage', 'مارک\u200cآپ درصدی'), ('custom_factor', 'ضریب سفارشی')], max_length=20, verbose_name='روش قیمت\u200cگذاری')),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='درصد تخفیف')),
                ('fixed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='قیمت ثابت')),
                ('markup_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='درصد مارک\u200cآپ')),
                ('custom_factor', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='ضریب سفارشی')),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='حداقل قیمت')),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='حداکثر قیمت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('priority', models.PositiveIntegerField(default=0, verbose_name='اولویت')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'قانون قیمت\u200cگذاری ایجنت',
                'verbose_name_plural': 'قوانین قیمت\u200cگذاری ایجنت\u200cها',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='Company name')),
                ('license_number', models.CharField(blank=True, max_length=100, verbose_name='License number')),
                ('business_address', models.TextField(blank=True, verbose_name='Business address')),
                ('business_phone', models.CharField(blank=True, max_length=20, verbose_name='Business phone')),
                ('business_email', models.EmailField(blank=True, max_length=254, verbose_name='Business email')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Commission rate (%)')),
                ('min_commission', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Minimum commission')),
                ('max_commission', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Maximum commission')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Is verified')),
                ('total_orders', models.PositiveIntegerField(default=0, verbose_name='Total orders')),
                ('total_commission_earned', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total commission earned')),
                ('total_commission_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total commission paid')),
                ('average_commission', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Average commission per order')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='Preferred payment method')),
                ('payment_account', models.CharField(blank=True, max_length=255, verbose_name='Payment account details')),
                ('payment_frequency', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], default='monthly', max_length=20, verbose_name='Payment frequency')),
            ],
            options={
                'verbose_name': 'Agent Profile',
                'verbose_name_plural': 'Agent Profiles',
            },
        ),
    ]
