# Generated by Django 5.0.2 on 2025-06-26 23:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('company_name', models.CharField(max_length=255, verbose_name='Company name')),
                ('license_number', models.CharField(blank=True, max_length=100, verbose_name='License number')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Is verified')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentCommission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('commission_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Commission rate (%)')),
                ('order_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Order amount')),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Commission amount')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Currency')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Payment date')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='Payment method')),
                ('payment_reference', models.CharField(blank=True, max_length=100, verbose_name='Payment reference')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to=settings.AUTH_USER_MODEL, verbose_name='Agent')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_commissions', to='orders.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Agent Commission',
                'verbose_name_plural': 'Agent Commissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='Company name')),
                ('license_number', models.CharField(blank=True, max_length=100, verbose_name='License number')),
                ('business_address', models.TextField(blank=True, verbose_name='Business address')),
                ('business_phone', models.CharField(blank=True, max_length=20, verbose_name='Business phone')),
                ('business_email', models.EmailField(blank=True, max_length=254, verbose_name='Business email')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Commission rate (%)')),
                ('min_commission', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Minimum commission')),
                ('max_commission', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Maximum commission')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Is verified')),
                ('total_orders', models.PositiveIntegerField(default=0, verbose_name='Total orders')),
                ('total_commission', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total commission earned')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Agent Profile',
                'verbose_name_plural': 'Agent Profiles',
            },
        ),
        migrations.CreateModel(
            name='AgentCustomer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Customer name')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Customer email')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Customer phone')),
                ('relationship_notes', models.TextField(blank=True, verbose_name='Relationship notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_customers', to=settings.AUTH_USER_MODEL, verbose_name='Agent')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_agent', to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Agent Customer',
                'verbose_name_plural': 'Agent Customers',
                'unique_together': {('agent', 'customer')},
            },
        ),
    ]
