# Generated by Django 5.0.2 on 2025-09-13 09:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentPricingRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('product_type', models.CharField(choices=[('tour', 'تور'), ('event', 'رویداد'), ('transfer', 'ترانسفر'), ('car_rental', 'اجاره ماشین')], max_length=20, verbose_name='نوع محصول')),
                ('pricing_method', models.CharField(choices=[('discount_percentage', 'تخفیف درصدی'), ('fixed_price', 'قیمت ثابت'), ('markup_percentage', 'مارک\u200cآپ درصدی'), ('custom_factor', 'ضریب سفارشی')], max_length=20, verbose_name='روش قیمت\u200cگذاری')),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='درصد تخفیف')),
                ('fixed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='قیمت ثابت')),
                ('markup_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='درصد مارک\u200cآپ')),
                ('custom_factor', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='ضریب سفارشی')),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='حداقل قیمت')),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='حداکثر قیمت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('priority', models.PositiveIntegerField(default=0, verbose_name='اولویت')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to=settings.AUTH_USER_MODEL, verbose_name='Agent')),
            ],
            options={
                'verbose_name': 'قانون قیمت\u200cگذاری ایجنت',
                'verbose_name_plural': 'قوانین قیمت\u200cگذاری ایجنت\u200cها',
                'ordering': ['-priority', '-created_at'],
                'unique_together': {('agent', 'product_type')},
            },
        ),
    ]
