# Generated by Django 5.0.2 on 2025-09-13 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agentpricingrule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentprofile',
            old_name='total_commission',
            new_name='total_commission_earned',
        ),
        migrations.RemoveField(
            model_name='agentcommission',
            name='payment_date',
        ),
        migrations.AddField(
            model_name='agentcommission',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Approved at'),
        ),
        migrations.AddField(
            model_name='agentcommission',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_commissions', to=settings.AUTH_USER_MODEL, verbose_name='Approved by'),
        ),
        migrations.AddField(
            model_name='agentcommission',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Paid at'),
        ),
        migrations.AddField(
            model_name='agentcommission',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_commissions', to=settings.AUTH_USER_MODEL, verbose_name='Paid by'),
        ),
        migrations.AddField(
            model_name='agentcommission',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Rejected at'),
        ),
        migrations.AddField(
            model_name='agentcommission',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_commissions', to=settings.AUTH_USER_MODEL, verbose_name='Rejected by'),
        ),
        migrations.AddField(
            model_name='agentcommission',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='Rejection reason'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='average_commission',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Average commission per order'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='payment_account',
            field=models.CharField(blank=True, max_length=255, verbose_name='Payment account details'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='payment_frequency',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], default='monthly', max_length=20, verbose_name='Payment frequency'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, verbose_name='Preferred payment method'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='total_commission_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total commission paid'),
        ),
        migrations.AlterField(
            model_name='agentcommission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
