# Generated by Django 5.0.2 on 2025-09-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_rename_total_commission_agentprofile_total_commission_earned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentcustomer',
            name='created_by_agent',
            field=models.BooleanField(default=True, verbose_name='Created by agent'),
        ),
        migrations.AddField(
            model_name='agentcustomer',
            name='customer_address',
            field=models.TextField(blank=True, verbose_name='Customer address'),
        ),
        migrations.AddField(
            model_name='agentcustomer',
            name='customer_birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Customer birth date'),
        ),
        migrations.AddField(
            model_name='agentcustomer',
            name='customer_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Customer city'),
        ),
        migrations.AddField(
            model_name='agentcustomer',
            name='customer_country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Customer country'),
        ),
        migrations.AddField(
            model_name='agentcustomer',
            name='customer_gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, verbose_name='Customer gender'),
        ),
        migrations.AddField(
            model_name='agentcustomer',
            name='customer_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked'), ('vip', 'VIP')], default='active', max_length=20, verbose_name='Customer status'),
        ),
        migrations.AddField(
            model_name='agentcustomer',
            name='customer_tier',
            field=models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='bronze', max_length=20, verbose_name='Customer tier'),
        ),
        migrations.AddField(
            model_name='agentcustomer',
            name='last_order_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last order date'),
        ),
        migrations.AddField(
            model_name='agentcustomer',
            name='marketing_consent',
            field=models.BooleanField(default=False, verbose_name='Marketing consent'),
        ),
        migrations.AddField(
            model_name='agentcustomer',
            name='preferred_contact_method',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS')], default='email', max_length=20, verbose_name='Preferred contact method'),
        ),
        migrations.AddField(
            model_name='agentcustomer',
            name='preferred_language',
            field=models.CharField(choices=[('fa', 'Persian'), ('en', 'English'), ('ar', 'Arabic')], default='fa', max_length=10, verbose_name='Preferred language'),
        ),
        migrations.AddField(
            model_name='agentcustomer',
            name='special_requirements',
            field=models.TextField(blank=True, verbose_name='Special requirements'),
        ),
        migrations.AddField(
            model_name='agentcustomer',
            name='total_orders',
            field=models.PositiveIntegerField(default=0, verbose_name='Total orders'),
        ),
        migrations.AddField(
            model_name='agentcustomer',
            name='total_spent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total spent'),
        ),
    ]
