# Generated by Django 5.0.2 on 2025-09-14 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_agentcustomer_created_by_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentcustomer',
            name='credentials_sent',
            field=models.BooleanField(default=False, verbose_name='Login credentials sent'),
        ),
        migrations.AddField(
            model_name='agentcustomer',
            name='credentials_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Credentials sent at'),
        ),
        migrations.AddField(
            model_name='agentcustomer',
            name='last_login_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last login at'),
        ),
        migrations.AddField(
            model_name='agentcustomer',
            name='login_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Login count'),
        ),
        migrations.AddField(
            model_name='agentcustomer',
            name='requires_verification',
            field=models.BooleanField(default=True, verbose_name='Requires email verification'),
        ),
    ]
