# Generated by Django 5.0.2 on 2025-09-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_fix_customer_gender_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentcustomer',
            name='customer_gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default=2, max_length=10, verbose_name='Customer gender'),
            preserve_default=False,
        ),
    ]
