# Generated by Django 5.2.6 on 2025-09-25 16:20

import django.db.models.deletion
import parler.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='responded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_responses', to=settings.AUTH_USER_MODEL, verbose_name='Responded By'),
        ),
        migrations.AddField(
            model_name='ctabuttontranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='shared.ctabutton'),
        ),
        migrations.AddField(
            model_name='ctafeaturetranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='shared.ctafeature'),
        ),
        migrations.AddField(
            model_name='ctafeature',
            name='cta_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='shared.ctasection', verbose_name='CTA Section'),
        ),
        migrations.AddField(
            model_name='ctabutton',
            name='cta_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='shared.ctasection', verbose_name='CTA Section'),
        ),
        migrations.AddField(
            model_name='ctasectiontranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='shared.ctasection'),
        ),
        migrations.AddField(
            model_name='faq',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='shared.faqcategory', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='faqcategorytranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='shared.faqcategory'),
        ),
        migrations.AddField(
            model_name='faqsettingstranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='shared.faqsettings'),
        ),
        migrations.AddField(
            model_name='footerlink',
            name='footer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='navigation_links', to='shared.footer', verbose_name='Footer'),
        ),
        migrations.AddField(
            model_name='footerlinktranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='shared.footerlink'),
        ),
        migrations.AddField(
            model_name='footertranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='shared.footer'),
        ),
        migrations.AddField(
            model_name='heroslidertranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='shared.heroslider'),
        ),
        migrations.AddField(
            model_name='staticpagetranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='shared.staticpage'),
        ),
        migrations.AddIndex(
            model_name='supportfaq',
            index=models.Index(fields=['category', 'is_active'], name='shared_supp_categor_f0fd8d_idx'),
        ),
        migrations.AddIndex(
            model_name='supportfaq',
            index=models.Index(fields=['order'], name='shared_supp_order_2c6c1b_idx'),
        ),
        migrations.AddField(
            model_name='transferbookingsectiontranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='shared.transferbookingsection'),
        ),
        migrations.AlterUniqueTogether(
            name='aboutfeaturetranslation',
            unique_together={('language_code', 'master')},
        ),
        migrations.AlterUniqueTogether(
            name='aboutsectiontranslation',
            unique_together={('language_code', 'master')},
        ),
        migrations.AlterUniqueTogether(
            name='aboutstatistictranslation',
            unique_together={('language_code', 'master')},
        ),
        migrations.AlterUniqueTogether(
            name='bannertranslation',
            unique_together={('language_code', 'master')},
        ),
        migrations.AlterUniqueTogether(
            name='ctabuttontranslation',
            unique_together={('language_code', 'master')},
        ),
        migrations.AlterUniqueTogether(
            name='ctafeaturetranslation',
            unique_together={('language_code', 'master')},
        ),
        migrations.AlterUniqueTogether(
            name='ctasectiontranslation',
            unique_together={('language_code', 'master')},
        ),
        migrations.AddIndex(
            model_name='faq',
            index=models.Index(fields=['category', 'order'], name='shared_faq_categor_9bbe58_idx'),
        ),
        migrations.AddIndex(
            model_name='faq',
            index=models.Index(fields=['is_featured', 'is_published'], name='shared_faq_is_feat_a21d6e_idx'),
        ),
        migrations.AddIndex(
            model_name='faq',
            index=models.Index(fields=['view_count'], name='shared_faq_view_co_0c1a4d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='faqcategorytranslation',
            unique_together={('language_code', 'master')},
        ),
        migrations.AlterUniqueTogether(
            name='faqsettingstranslation',
            unique_together={('language_code', 'master')},
        ),
        migrations.AlterUniqueTogether(
            name='footerlinktranslation',
            unique_together={('language_code', 'master')},
        ),
        migrations.AlterUniqueTogether(
            name='footertranslation',
            unique_together={('language_code', 'master')},
        ),
        migrations.AlterUniqueTogether(
            name='heroslidertranslation',
            unique_together={('language_code', 'master')},
        ),
        migrations.AlterUniqueTogether(
            name='staticpagetranslation',
            unique_together={('language_code', 'master')},
        ),
        migrations.AlterUniqueTogether(
            name='transferbookingsectiontranslation',
            unique_together={('language_code', 'master')},
        ),
    ]
