# Generated by Django 5.0.2 on 2025-08-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_add_slug_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='slug',
            field=models.SlugField(blank=True, null=True, max_length=255, unique=True, verbose_name='Slug'),
        ),
    ]
