# Generated by Django 5.1.4 on 2025-10-17 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0003_navigationmenu_navigationmenutranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='default_hero_button_text',
            field=models.CharField(default='Explore Tours', help_text='Button text shown when no hero slides exist', max_length=50, verbose_name='Default Hero Button Text'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_hero_button_url',
            field=models.CharField(default='/tours', help_text='Button URL when no hero slides exist', max_length=200, verbose_name='Default Hero Button URL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_hero_description',
            field=models.TextField(default='Your gateway to amazing travel experiences', help_text='Description shown when no hero slides exist', verbose_name='Default Hero Description'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_hero_subtitle',
            field=models.CharField(default='Discover amazing places', help_text='Subtitle shown when no hero slides exist', max_length=300, verbose_name='Default Hero Subtitle'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_hero_title',
            field=models.CharField(default='Welcome to Peykan Tourism', help_text='Title shown when no hero slides exist', max_length=200, verbose_name='Default Hero Title'),
        ),
    ]
