# Generated by Django 5.0.2 on 2025-08-31 10:47

import django.db.models.deletion
import parler.fields
import parler.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0004_contactinfo_staticpage_remove_faq_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('icon', models.CharField(blank=True, help_text='CSS class for icon (e.g., fas fa-question-circle)', max_length=50, verbose_name='Icon Class')),
                ('color', models.CharField(default='#007bff', help_text='Hex color code for category', max_length=7, verbose_name='Color')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
            ],
            options={
                'verbose_name': 'FAQ Category',
                'verbose_name_plural': 'FAQ Categories',
                'db_table': 'shared_faq_category',
                'ordering': ['order', 'created_at'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FAQCategoryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=100, verbose_name='Category Name')),
                ('description', models.TextField(blank=True, verbose_name='Category Description')),
            ],
            options={
                'verbose_name': 'FAQ Category Translation',
                'db_table': 'shared_faq_category_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['category__order', 'order', '-is_featured', 'created_at'], 'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQs'},
        ),
        migrations.AddField(
            model_name='faq',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Featured FAQs appear at the top', verbose_name='Is Featured'),
        ),
        migrations.AddField(
            model_name='faq',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Is Published'),
        ),
        migrations.AddField(
            model_name='faq',
            name='keywords',
            field=models.CharField(blank=True, help_text='Keywords to help users find this FAQ', max_length=255, verbose_name='Search Keywords'),
        ),
        migrations.AddField(
            model_name='faq',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags for categorization', max_length=255, verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='faq',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='View Count'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=500, verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='shared.faqcategory', verbose_name='Category'),
        ),
        migrations.AddIndex(
            model_name='faq',
            index=models.Index(fields=['category', 'order'], name='shared_faq_categor_9bbe58_idx'),
        ),
        migrations.AddIndex(
            model_name='faq',
            index=models.Index(fields=['is_featured', 'is_published'], name='shared_faq_is_feat_a21d6e_idx'),
        ),
        migrations.AddIndex(
            model_name='faq',
            index=models.Index(fields=['view_count'], name='shared_faq_view_co_0c1a4d_idx'),
        ),
        migrations.AddField(
            model_name='faqcategorytranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='shared.faqcategory'),
        ),
        migrations.AlterUniqueTogether(
            name='faqcategorytranslation',
            unique_together={('language_code', 'master')},
        ),
    ]
