# Generated by Django 5.1.4 on 2025-10-25 17:46

import django.core.validators
import django.db.models.deletion
import parler.fields
import parler.models
import shared.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0004_sitesettings_default_hero_button_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('file', models.FileField(help_text='Upload PDF file (max 50MB)', upload_to='catalogs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), shared.models.validate_file_size], verbose_name='PDF File')),
                ('catalog_type', models.CharField(choices=[('tour', 'Tour Catalog'), ('event', 'Event Catalog'), ('general', 'General Catalog')], default='general', max_length=20, verbose_name='Catalog Type')),
                ('version', models.CharField(blank=True, help_text='e.g., 2025-1, v1.0, etc.', max_length=50, verbose_name='Version')),
                ('file_size', models.PositiveIntegerField(default=0, help_text='Automatically calculated on save', verbose_name='File Size (bytes)')),
                ('is_featured', models.BooleanField(default=False, help_text='Featured catalog will be shown as default', verbose_name='Is Featured')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='Download Count')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='View Count')),
                ('meta_description', models.TextField(blank=True, max_length=160, verbose_name='Meta Description')),
            ],
            options={
                'verbose_name': 'Catalog File',
                'verbose_name_plural': 'Catalog Files',
                'ordering': ['-is_featured', 'display_order', '-created_at'],
                'indexes': [models.Index(fields=['catalog_type', 'is_active'], name='shared_cata_catalog_a3825e_idx'), models.Index(fields=['is_featured', 'is_active'], name='shared_cata_is_feat_d582d6_idx')],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CatalogFileTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='shared.catalogfile')),
            ],
            options={
                'verbose_name': 'Catalog File Translation',
                'db_table': 'shared_catalogfile_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
