# Generated by Django 5.0.2 on 2025-08-31 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0005_faqcategory_faqcategorytranslation_alter_faq_options_and_more'),
    ]

    operations = [
        # Add keywords field to FAQ
        migrations.AddField(
            model_name='faq',
            name='keywords',
            field=models.CharField(blank=True, help_text='Keywords to help users find this FAQ', max_length=255, verbose_name='Search Keywords'),
        ),
    ]
