# Generated by Django 5.0.2 on 2025-09-01 09:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0006_auto_20250831_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportFAQ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('category', models.CharField(choices=[('booking', 'Booking'), ('cancellation', 'Cancellation'), ('transfer', 'Transfer'), ('general', 'General Support')], max_length=20, verbose_name='Category')),
                ('question', models.CharField(max_length=500, verbose_name='Question')),
                ('whatsapp_message', models.TextField(help_text='Pre-filled message that will be sent to WhatsApp', verbose_name='WhatsApp Message')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Support FAQ',
                'verbose_name_plural': 'Support FAQs',
                'db_table': 'shared_support_faq',
                'ordering': ['category', 'order', 'created_at'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='shared_supp_categor_f0fd8d_idx'), models.Index(fields=['order'], name='shared_supp_order_2c6c1b_idx')],
            },
        ),
    ]
