# Generated by Django 5.0.2 on 2025-09-08 18:12

import django.db.models.deletion
import parler.fields
import parler.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0007_supportfaq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('banner_type', models.CharField(choices=[('homepage_top', 'Homepage Top'), ('homepage_bottom', 'Homepage Bottom'), ('tour_detail', 'Tour Detail Page'), ('event_detail', 'Event Detail Page'), ('seasonal', 'Seasonal Banner'), ('promotion', 'Promotional Banner'), ('sidebar', 'Sidebar Banner')], max_length=20, verbose_name='Banner Type')),
                ('position', models.CharField(choices=[('top', 'Top'), ('middle', 'Middle'), ('bottom', 'Bottom'), ('sidebar', 'Sidebar'), ('popup', 'Popup')], default='top', max_length=20, verbose_name='Position')),
                ('image', models.ImageField(help_text='Recommended size: 1200x400px for banners', upload_to='banners/', verbose_name='Banner Image')),
                ('mobile_image', models.ImageField(blank=True, help_text='Optional mobile-specific image', null=True, upload_to='banners/mobile/', verbose_name='Mobile Banner Image')),
                ('link_url', models.URLField(blank=True, verbose_name='Link URL')),
                ('link_target', models.CharField(choices=[('_self', 'Same Window'), ('_blank', 'New Window')], default='_self', max_length=20, verbose_name='Link Target')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End Date')),
                ('show_on_pages', models.JSONField(blank=True, default=list, help_text='List of page URLs or patterns where this banner should appear', verbose_name='Show on Pages')),
                ('show_for_authenticated', models.BooleanField(default=True, verbose_name='Show for Authenticated Users')),
                ('show_for_anonymous', models.BooleanField(default=True, verbose_name='Show for Anonymous Users')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='View Count')),
                ('click_count', models.PositiveIntegerField(default=0, verbose_name='Click Count')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['display_order', 'created_at'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HeroSlider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('desktop_image', models.ImageField(help_text='Recommended size: 1920x1080px for desktop screens', upload_to='hero/desktop/', verbose_name='Desktop Image (1920x1080)')),
                ('tablet_image', models.ImageField(help_text='Recommended size: 1024x768px for tablet screens', upload_to='hero/tablet/', verbose_name='Tablet Image (1024x768)')),
                ('mobile_image', models.ImageField(help_text='Recommended size: 768x1024px for mobile screens', upload_to='hero/mobile/', verbose_name='Mobile Image (768x1024)')),
                ('button_url', models.URLField(verbose_name='Button URL')),
                ('button_type', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('outline', 'Outline')], default='primary', max_length=20, verbose_name='Button Type')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('display_duration', models.PositiveIntegerField(default=5000, help_text='How long this slide should be displayed in milliseconds', verbose_name='Display Duration (ms)')),
                ('show_for_authenticated', models.BooleanField(default=True, verbose_name='Show for Authenticated Users')),
                ('show_for_anonymous', models.BooleanField(default=True, verbose_name='Show for Anonymous Users')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End Date')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='View Count')),
                ('click_count', models.PositiveIntegerField(default=0, verbose_name='Click Count')),
            ],
            options={
                'verbose_name': 'Hero Slide',
                'verbose_name_plural': 'Hero Slides',
                'ordering': ['order', 'created_at'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ImageOptimization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('original_image', models.ImageField(upload_to='originals/', verbose_name='Original Image')),
                ('image_type', models.CharField(choices=[('hero', 'Hero Image'), ('tour', 'Tour Image'), ('event', 'Event Image'), ('banner', 'Banner Image'), ('profile', 'Profile Image'), ('gallery', 'Gallery Image')], max_length=20, verbose_name='Image Type')),
                ('desktop_version', models.ImageField(blank=True, null=True, upload_to='optimized/desktop/', verbose_name='Desktop Version')),
                ('tablet_version', models.ImageField(blank=True, null=True, upload_to='optimized/tablet/', verbose_name='Tablet Version')),
                ('mobile_version', models.ImageField(blank=True, null=True, upload_to='optimized/mobile/', verbose_name='Mobile Version')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='optimized/thumbnail/', verbose_name='Thumbnail')),
                ('original_width', models.PositiveIntegerField(verbose_name='Original Width')),
                ('original_height', models.PositiveIntegerField(verbose_name='Original Height')),
                ('original_size', models.PositiveIntegerField(verbose_name='Original Size (bytes)')),
                ('quality_desktop', models.PositiveIntegerField(default=85, verbose_name='Desktop Quality')),
                ('quality_tablet', models.PositiveIntegerField(default=80, verbose_name='Tablet Quality')),
                ('quality_mobile', models.PositiveIntegerField(default=75, verbose_name='Mobile Quality')),
                ('optimized_size_desktop', models.PositiveIntegerField(default=0, verbose_name='Optimized Desktop Size')),
                ('optimized_size_tablet', models.PositiveIntegerField(default=0, verbose_name='Optimized Tablet Size')),
                ('optimized_size_mobile', models.PositiveIntegerField(default=0, verbose_name='Optimized Mobile Size')),
                ('optimization_completed', models.BooleanField(default=False, verbose_name='Optimization Completed')),
            ],
            options={
                'verbose_name': 'Image Optimization',
                'verbose_name_plural': 'Image Optimizations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('site_name', models.CharField(default='Peykan Tourism', max_length=100, verbose_name='Site Name')),
                ('site_description', models.TextField(blank=True, verbose_name='Site Description')),
                ('default_language', models.CharField(default='fa', max_length=10, verbose_name='Default Language')),
                ('default_phone', models.CharField(blank=True, max_length=20, verbose_name='Default Phone Number')),
                ('default_email', models.EmailField(blank=True, max_length=254, verbose_name='Default Email')),
                ('default_hero_image', models.ImageField(blank=True, help_text='Fallback image for hero section', null=True, upload_to='defaults/hero/', verbose_name='Default Hero Image')),
                ('default_tour_image', models.ImageField(blank=True, help_text='Fallback image for tours', null=True, upload_to='defaults/tours/', verbose_name='Default Tour Image')),
                ('default_event_image', models.ImageField(blank=True, help_text='Fallback image for events', null=True, upload_to='defaults/events/', verbose_name='Default Event Image')),
                ('default_meta_image', models.ImageField(blank=True, help_text='Default image for social media sharing', null=True, upload_to='defaults/meta/', verbose_name='Default Meta Image')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='Maintenance Mode')),
                ('maintenance_message', models.TextField(blank=True, help_text='Message to show when site is in maintenance mode', verbose_name='Maintenance Message')),
                ('default_meta_title', models.CharField(blank=True, max_length=60, verbose_name='Default Meta Title')),
                ('default_meta_description', models.CharField(blank=True, max_length=160, verbose_name='Default Meta Description')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='BannerTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('alt_text', models.CharField(max_length=200, verbose_name='Alt Text')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='shared.banner')),
            ],
            options={
                'verbose_name': 'Banner Translation',
                'db_table': 'shared_banner_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HeroSliderTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('subtitle', models.CharField(max_length=300, verbose_name='Subtitle')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('button_text', models.CharField(default='Learn More', max_length=50, verbose_name='Button Text')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='shared.heroslider')),
            ],
            options={
                'verbose_name': 'Hero Slide Translation',
                'db_table': 'shared_heroslider_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
