# Generated by Django 5.0.2 on 2025-09-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0009_aboutfeature_aboutsection_aboutstatistic_ctasection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslider',
            name='autoplay_video',
            field=models.BooleanField(default=False, help_text='Automatically play video when slide is active', verbose_name='Autoplay Video'),
        ),
        migrations.AddField(
            model_name='heroslider',
            name='show_video_controls',
            field=models.BooleanField(default=False, help_text='Show video player controls (play, pause, volume, etc.)', verbose_name='Show Video Controls'),
        ),
        migrations.AddField(
            model_name='heroslider',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload MP4, WebM, or OGV video file (max 50MB)', null=True, upload_to='hero/videos/', verbose_name='Video File'),
        ),
        migrations.AddField(
            model_name='heroslider',
            name='video_loop',
            field=models.BooleanField(default=True, help_text='Loop video playback continuously', verbose_name='Loop Video'),
        ),
        migrations.AddField(
            model_name='heroslider',
            name='video_muted',
            field=models.BooleanField(default=True, help_text='Start video muted (recommended for autoplay)', verbose_name='Video Muted'),
        ),
        migrations.AddField(
            model_name='heroslider',
            name='video_thumbnail',
            field=models.ImageField(blank=True, help_text='Custom thumbnail image for video (optional)', null=True, upload_to='hero/video_thumbnails/', verbose_name='Video Thumbnail'),
        ),
        migrations.AddField(
            model_name='heroslider',
            name='video_type',
            field=models.CharField(choices=[('none', 'No Video'), ('file', 'Upload Video File'), ('url', 'External Video URL')], default='none', help_text='Choose whether to use a video file or external video URL', max_length=10, verbose_name='Video Type'),
        ),
        migrations.AddField(
            model_name='heroslider',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube, Vimeo, or direct video URL', verbose_name='Video URL'),
        ),
        migrations.AlterField(
            model_name='heroslider',
            name='desktop_image',
            field=models.ImageField(blank=True, help_text='Recommended size: 1920x1080px for desktop screens', null=True, upload_to='hero/desktop/', verbose_name='Desktop Image (1920x1080)'),
        ),
        migrations.AlterField(
            model_name='heroslider',
            name='mobile_image',
            field=models.ImageField(blank=True, help_text='Recommended size: 768x1024px for mobile screens', null=True, upload_to='hero/mobile/', verbose_name='Mobile Image (768x1024)'),
        ),
        migrations.AlterField(
            model_name='heroslider',
            name='tablet_image',
            field=models.ImageField(blank=True, help_text='Recommended size: 1024x768px for tablet screens', null=True, upload_to='hero/tablet/', verbose_name='Tablet Image (1024x768)'),
        ),
    ]
