# Generated by Django 5.0.2 on 2025-07-09 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_eventcategory_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='ticket_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='events.tickettype', verbose_name='Ticket type'),
        ),
    ]
