# Generated by Django 5.0.2 on 2025-07-09 19:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_seat_ticket_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('name', models.CharField(max_length=50, verbose_name='Section name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('total_capacity', models.PositiveIntegerField(verbose_name='Total capacity')),
                ('available_capacity', models.PositiveIntegerField(verbose_name='Available capacity')),
                ('reserved_capacity', models.PositiveIntegerField(default=0, verbose_name='Reserved capacity')),
                ('sold_capacity', models.PositiveIntegerField(default=0, verbose_name='Sold capacity')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Base price')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Currency')),
                ('is_wheelchair_accessible', models.BooleanField(default=False, verbose_name='Wheelchair accessible')),
                ('is_premium', models.BooleanField(default=False, verbose_name='Premium section')),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='events.eventperformance', verbose_name='Performance')),
            ],
            options={
                'verbose_name': 'Event Section',
                'verbose_name_plural': 'Event Sections',
                'ordering': ['name'],
                'unique_together': {('performance', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SectionTicketType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('allocated_capacity', models.PositiveIntegerField(verbose_name='Allocated capacity')),
                ('available_capacity', models.PositiveIntegerField(verbose_name='Available capacity')),
                ('reserved_capacity', models.PositiveIntegerField(default=0, verbose_name='Reserved capacity')),
                ('sold_capacity', models.PositiveIntegerField(default=0, verbose_name='Sold capacity')),
                ('price_modifier', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='Price modifier')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='events.eventsection', verbose_name='Section')),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_allocations', to='events.tickettype', verbose_name='Ticket type')),
            ],
            options={
                'verbose_name': 'Section Ticket Type',
                'verbose_name_plural': 'Section Ticket Types',
                'unique_together': {('section', 'ticket_type')},
            },
        ),
    ]
