# Generated by Django 5.0.2 on 2025-08-14 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_eventdiscount_eventfee_eventpricingrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='reservation_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Reservation expires at'),
        ),
        migrations.AddField(
            model_name='seat',
            name='reservation_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Reservation ID'),
        ),
    ]
