# Generated by Django 5.0.2 on 2025-08-20 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_add_cancellation_policy'),
        ('events', '0007_seat_reservation_expires_at_seat_reservation_id'),
    ]

    operations = [
    ]
