# Generated by Django 5.0.2 on 2025-08-22 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_merge_20250820_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventsection',
            name='available_capacity',
        ),
        migrations.RemoveField(
            model_name='eventsection',
            name='reserved_capacity',
        ),
        migrations.RemoveField(
            model_name='eventsection',
            name='sold_capacity',
        ),
    ]
