# Generated by Django 5.0.2 on 2025-08-24 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_remove_old_capacity_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectiontickettype',
            name='allocated_capacity',
        ),
        migrations.RemoveField(
            model_name='sectiontickettype',
            name='available_capacity',
        ),
        migrations.RemoveField(
            model_name='sectiontickettype',
            name='reserved_capacity',
        ),
        migrations.RemoveField(
            model_name='sectiontickettype',
            name='sold_capacity',
        ),
    ]
