# Generated by Django 5.0.2 on 2025-08-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_remove_capacity_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Image'),
        ),
    ]
