# Generated by Django 5.0.2 on 2025-09-04 18:24

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_event_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCancellationPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('hours_before', models.PositiveIntegerField(help_text='Number of hours before event start when this policy applies', verbose_name='Hours before event start')),
                ('refund_percentage', models.PositiveIntegerField(help_text='Percentage of refund for cancellations within this time frame', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Refund percentage')),
                ('description', models.TextField(blank=True, help_text='Human-readable description of this policy', verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_policies', to='events.event', verbose_name='Event')),
            ],
            options={
                'verbose_name': 'Event Cancellation Policy',
                'verbose_name_plural': 'Event Cancellation Policies',
                'ordering': ['-hours_before'],
                'unique_together': {('event', 'hours_before')},
            },
        ),
    ]
