# Generated by Django 5.0.2 on 2025-09-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_eventcancellationpolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_seasonal',
            field=models.BooleanField(default=False, help_text='Mark as seasonal event (summer/winter specials, holidays, etc.)', verbose_name='Is seasonal'),
        ),
        migrations.AddField(
            model_name='event',
            name='is_special',
            field=models.BooleanField(default=False, help_text='Mark as special event for premium display on homepage', verbose_name='Is special'),
        ),
    ]
