# Generated by Django 5.0.2 on 2025-06-26 23:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('order_number', models.CharField(max_length=20, unique=True, verbose_name='Order number')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('paid', 'Paid'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20, verbose_name='Status')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20, verbose_name='Payment status')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='Payment method')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Tax amount')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Discount amount')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total amount')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Currency')),
                ('agent_commission_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Agent commission rate (%)')),
                ('agent_commission_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Agent commission amount')),
                ('commission_paid', models.BooleanField(default=False, verbose_name='Commission paid')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Customer name')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Customer email')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Customer phone')),
                ('billing_address', models.TextField(blank=True, verbose_name='Billing address')),
                ('billing_city', models.CharField(blank=True, max_length=100, verbose_name='Billing city')),
                ('billing_country', models.CharField(blank=True, max_length=100, verbose_name='Billing country')),
                ('customer_notes', models.TextField(blank=True, verbose_name='Customer notes')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Internal notes')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('field_name', models.CharField(max_length=100, verbose_name='Field name')),
                ('old_value', models.TextField(blank=True, verbose_name='Old value')),
                ('new_value', models.TextField(blank=True, verbose_name='New value')),
                ('change_reason', models.TextField(blank=True, verbose_name='Change reason')),
            ],
            options={
                'verbose_name': 'Order History',
                'verbose_name_plural': 'Order History',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('product_type', models.CharField(choices=[('tour', 'Tour'), ('event', 'Event'), ('transfer', 'Transfer')], max_length=20, verbose_name='Product type')),
                ('product_id', models.UUIDField(verbose_name='Product ID')),
                ('product_title', models.CharField(max_length=255, verbose_name='Product title')),
                ('product_slug', models.CharField(max_length=255, verbose_name='Product slug')),
                ('booking_date', models.DateField(verbose_name='Booking date')),
                ('booking_time', models.TimeField(verbose_name='Booking time')),
                ('variant_id', models.UUIDField(blank=True, null=True, verbose_name='Variant ID')),
                ('variant_name', models.CharField(blank=True, max_length=100, verbose_name='Variant name')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit price')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total price')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Currency')),
                ('selected_options', models.JSONField(default=list, verbose_name='Selected options')),
                ('options_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Options total')),
                ('booking_data', models.JSONField(default=dict, verbose_name='Booking data')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'ordering': ['created_at'],
            },
        ),
    ]
