# Generated by Django 5.2.6 on 2025-09-25 16:20

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('order_number', models.CharField(max_length=20, unique=True, verbose_name='Order number')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('paid', 'Paid'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20, verbose_name='Status')),
                ('is_capacity_reserved', models.BooleanField(default=False, verbose_name='Is capacity reserved')),
                ('capacity_reserved_at', models.DateTimeField(blank=True, null=True, verbose_name='Capacity reserved at')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20, verbose_name='Payment status')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='Payment method')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('service_fee_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Service fee amount')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Tax amount')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Discount amount')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total amount')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Currency')),
                ('agent_commission_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Agent commission rate (%)')),
                ('agent_commission_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Agent commission amount')),
                ('commission_paid', models.BooleanField(default=False, verbose_name='Commission paid')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Customer name')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Customer email')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Customer phone')),
                ('billing_address', models.TextField(default='', verbose_name='Billing address')),
                ('billing_city', models.CharField(default='', max_length=100, verbose_name='Billing city')),
                ('billing_country', models.CharField(default='', max_length=100, verbose_name='Billing country')),
                ('customer_notes', models.TextField(default='', verbose_name='Customer notes')),
                ('internal_notes', models.TextField(default='', verbose_name='Internal notes')),
                ('admin_notes', models.TextField(default='', verbose_name='Admin notes')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Payment date')),
                ('payment_reference', models.CharField(default='', max_length=100, verbose_name='Payment reference/Transaction ID')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('field_name', models.CharField(max_length=100, verbose_name='Field name')),
                ('old_value', models.TextField(blank=True, verbose_name='Old value')),
                ('new_value', models.TextField(blank=True, verbose_name='New value')),
                ('change_reason', models.TextField(blank=True, verbose_name='Change reason')),
            ],
            options={
                'verbose_name': 'Order History',
                'verbose_name_plural': 'Order History',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('product_type', models.CharField(choices=[('tour', 'Tour'), ('event', 'Event'), ('transfer', 'Transfer'), ('car_rental', 'Car Rental')], max_length=20, verbose_name='Product type')),
                ('product_id', models.UUIDField(verbose_name='Product ID')),
                ('product_title', models.CharField(max_length=255, verbose_name='Product title')),
                ('product_slug', models.CharField(max_length=255, verbose_name='Product slug')),
                ('booking_date', models.DateField(verbose_name='Booking date')),
                ('booking_time', models.TimeField(verbose_name='Booking time')),
                ('pickup_date', models.DateField(blank=True, null=True, verbose_name='Pickup date')),
                ('dropoff_date', models.DateField(blank=True, null=True, verbose_name='Dropoff date')),
                ('pickup_time', models.TimeField(blank=True, null=True, verbose_name='Pickup time')),
                ('dropoff_time', models.TimeField(blank=True, null=True, verbose_name='Dropoff time')),
                ('pickup_location_type', models.CharField(choices=[('predefined', 'Predefined Location'), ('custom', 'Custom Location')], default='predefined', max_length=20, verbose_name='Pickup location type')),
                ('pickup_location_id', models.UUIDField(blank=True, null=True, verbose_name='Pickup location ID')),
                ('pickup_location_custom', models.CharField(blank=True, max_length=255, null=True, verbose_name='Custom pickup location')),
                ('pickup_location_coordinates', models.JSONField(blank=True, default=dict, verbose_name='Pickup location coordinates')),
                ('dropoff_location_type', models.CharField(choices=[('predefined', 'Predefined Location'), ('custom', 'Custom Location'), ('same_as_pickup', 'Same as Pickup')], default='same_as_pickup', max_length=20, verbose_name='Dropoff location type')),
                ('dropoff_location_id', models.UUIDField(blank=True, null=True, verbose_name='Dropoff location ID')),
                ('dropoff_location_custom', models.CharField(blank=True, max_length=255, null=True, verbose_name='Custom dropoff location')),
                ('dropoff_location_coordinates', models.JSONField(blank=True, default=dict, verbose_name='Dropoff location coordinates')),
                ('variant_id', models.UUIDField(blank=True, null=True, verbose_name='Variant ID')),
                ('variant_name', models.CharField(blank=True, max_length=100, verbose_name='Variant name')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit price')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total price')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Currency')),
                ('selected_options', models.JSONField(default=list, verbose_name='Selected options')),
                ('options_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Options total')),
                ('booking_data', models.JSONField(default=dict, verbose_name='Booking data')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'ordering': ['created_at'],
            },
        ),
    ]
