# Generated by Django 5.0.2 on 2025-09-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='capacity_reserved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Capacity reserved at'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_capacity_reserved',
            field=models.BooleanField(default=False, verbose_name='Is capacity reserved'),
        ),
    ]
