# Generated by Django 5.0.2 on 2025-09-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_admin_notes_order_payment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='admin_notes',
            field=models.TextField(default='', verbose_name='Admin notes'),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_address',
            field=models.TextField(default='', verbose_name='Billing address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_city',
            field=models.CharField(default='', max_length=100, verbose_name='Billing city'),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_country',
            field=models.CharField(default='', max_length=100, verbose_name='Billing country'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_notes',
            field=models.TextField(default='', verbose_name='Customer notes'),
        ),
        migrations.AlterField(
            model_name='order',
            name='internal_notes',
            field=models.TextField(default='', verbose_name='Internal notes'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_reference',
            field=models.CharField(default='', max_length=100, verbose_name='Payment reference/Transaction ID'),
        ),
    ]
