# Generated by Django 5.0.2 on 2025-09-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_admin_notes_alter_order_billing_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='service_fee_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Service fee amount'),
        ),
    ]
