# Generated by Django 5.0.2 on 2025-09-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_add_service_fee_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='dropoff_date',
            field=models.DateField(blank=True, null=True, verbose_name='Dropoff date'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='dropoff_location_coordinates',
            field=models.JSONField(blank=True, default=dict, verbose_name='Dropoff location coordinates'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='dropoff_location_custom',
            field=models.CharField(blank=True, max_length=255, verbose_name='Custom dropoff location'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='dropoff_location_id',
            field=models.UUIDField(blank=True, null=True, verbose_name='Dropoff location ID'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='dropoff_location_type',
            field=models.CharField(choices=[('predefined', 'Predefined Location'), ('custom', 'Custom Location'), ('same_as_pickup', 'Same as Pickup')], default='same_as_pickup', max_length=20, verbose_name='Dropoff location type'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='dropoff_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Dropoff time'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='pickup_date',
            field=models.DateField(blank=True, null=True, verbose_name='Pickup date'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='pickup_location_coordinates',
            field=models.JSONField(blank=True, default=dict, verbose_name='Pickup location coordinates'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='pickup_location_custom',
            field=models.CharField(blank=True, max_length=255, verbose_name='Custom pickup location'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='pickup_location_id',
            field=models.UUIDField(blank=True, null=True, verbose_name='Pickup location ID'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='pickup_location_type',
            field=models.CharField(choices=[('predefined', 'Predefined Location'), ('custom', 'Custom Location')], default='predefined', max_length=20, verbose_name='Pickup location type'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='pickup_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Pickup time'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_type',
            field=models.CharField(choices=[('tour', 'Tour'), ('event', 'Event'), ('transfer', 'Transfer'), ('car_rental', 'Car Rental')], max_length=20, verbose_name='Product type'),
        ),
    ]
