# Generated by Django 5.0.2 on 2025-09-10 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_add_car_rental_fields'),
        ('orders', '0007_orderitem_dropoff_date_and_more'),
    ]

    operations = [
    ]
