# Generated by Django 5.0.2 on 2025-09-11 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_merge_20250910_1934'),
    ]

    operations = [
        migrations.RunSQL(
            """
            -- Add car rental fields to orderitem table
            ALTER TABLE orders_orderitem ADD COLUMN pickup_date date NULL;
            ALTER TABLE orders_orderitem ADD COLUMN dropoff_date date NULL;
            ALTER TABLE orders_orderitem ADD COLUMN pickup_time time NULL;
            ALTER TABLE orders_orderitem ADD COLUMN dropoff_time time NULL;
            ALTER TABLE orders_orderitem ADD COLUMN pickup_location_type varchar(20) DEFAULT 'predefined' NOT NULL;
            ALTER TABLE orders_orderitem ADD COLUMN pickup_location_id char(32) NULL;
            ALTER TABLE orders_orderitem ADD COLUMN pickup_location_custom varchar(255) DEFAULT '' NOT NULL;
            ALTER TABLE orders_orderitem ADD COLUMN pickup_location_coordinates text DEFAULT '{}' NOT NULL;
            ALTER TABLE orders_orderitem ADD COLUMN dropoff_location_type varchar(20) DEFAULT 'same_as_pickup' NOT NULL;
            ALTER TABLE orders_orderitem ADD COLUMN dropoff_location_id char(32) NULL;
            ALTER TABLE orders_orderitem ADD COLUMN dropoff_location_custom varchar(255) DEFAULT '' NOT NULL;
            ALTER TABLE orders_orderitem ADD COLUMN dropoff_location_coordinates text DEFAULT '{}' NOT NULL;
            """,
            reverse_sql="""
            -- Remove car rental fields
            ALTER TABLE orders_orderitem DROP COLUMN pickup_date;
            ALTER TABLE orders_orderitem DROP COLUMN dropoff_date;
            ALTER TABLE orders_orderitem DROP COLUMN pickup_time;
            ALTER TABLE orders_orderitem DROP COLUMN dropoff_time;
            ALTER TABLE orders_orderitem DROP COLUMN pickup_location_type;
            ALTER TABLE orders_orderitem DROP COLUMN pickup_location_id;
            ALTER TABLE orders_orderitem DROP COLUMN pickup_location_custom;
            ALTER TABLE orders_orderitem DROP COLUMN pickup_location_coordinates;
            ALTER TABLE orders_orderitem DROP COLUMN dropoff_location_type;
            ALTER TABLE orders_orderitem DROP COLUMN dropoff_location_id;
            ALTER TABLE orders_orderitem DROP COLUMN dropoff_location_custom;
            ALTER TABLE orders_orderitem DROP COLUMN dropoff_location_coordinates;
            """
        ),
    ]
