# Generated by Django 5.0.2 on 2025-09-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_add_car_rental_fields_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='dropoff_location_custom',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Custom dropoff location'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='pickup_location_custom',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Custom pickup location'),
        ),
    ]
