# Generated by Django 5.2.6 on 2025-09-25 16:20

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('session_id', models.CharField(max_length=40, unique=True, verbose_name='Session ID')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Currency')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('expires_at', models.DateTimeField(verbose_name='Expires at')),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('product_type', models.CharField(choices=[('tour', 'Tour'), ('event', 'Event'), ('transfer', 'Transfer'), ('car_rental', 'Car Rental')], max_length=20, verbose_name='Product type')),
                ('product_id', models.UUIDField(verbose_name='Product ID')),
                ('booking_date', models.DateField(verbose_name='Booking date')),
                ('booking_time', models.TimeField(verbose_name='Booking time')),
                ('pickup_date', models.DateField(blank=True, null=True, verbose_name='Pickup date')),
                ('dropoff_date', models.DateField(blank=True, null=True, verbose_name='Dropoff date')),
                ('pickup_time', models.TimeField(blank=True, null=True, verbose_name='Pickup time')),
                ('dropoff_time', models.TimeField(blank=True, null=True, verbose_name='Dropoff time')),
                ('pickup_location_type', models.CharField(choices=[('predefined', 'Predefined Location'), ('custom', 'Custom Location')], default='predefined', max_length=20, verbose_name='Pickup location type')),
                ('pickup_location_id', models.UUIDField(blank=True, null=True, verbose_name='Pickup location ID')),
                ('pickup_location_custom', models.CharField(blank=True, max_length=255, null=True, verbose_name='Custom pickup location')),
                ('pickup_location_coordinates', models.JSONField(blank=True, default=dict, verbose_name='Pickup location coordinates')),
                ('dropoff_location_type', models.CharField(choices=[('predefined', 'Predefined Location'), ('custom', 'Custom Location'), ('same_as_pickup', 'Same as Pickup')], default='same_as_pickup', max_length=20, verbose_name='Dropoff location type')),
                ('dropoff_location_id', models.UUIDField(blank=True, null=True, verbose_name='Dropoff location ID')),
                ('dropoff_location_custom', models.CharField(blank=True, max_length=255, null=True, verbose_name='Custom dropoff location')),
                ('dropoff_location_coordinates', models.JSONField(blank=True, default=dict, verbose_name='Dropoff location coordinates')),
                ('variant_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Variant ID')),
                ('variant_name', models.CharField(blank=True, max_length=100, verbose_name='Variant name')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit price')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total price')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Currency')),
                ('selected_options', models.JSONField(default=list, verbose_name='Selected options')),
                ('options_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Options total')),
                ('booking_data', models.JSONField(default=dict, verbose_name='Booking data')),
                ('is_reserved', models.BooleanField(default=False, verbose_name='Is reserved')),
                ('reservation_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Reservation expires at')),
            ],
            options={
                'verbose_name': 'Cart Item',
                'verbose_name_plural': 'Cart Items',
                'ordering': ['created_at'],
            },
        ),
    ]
