# Generated by Django 5.0.2 on 2025-06-26 23:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('session_id', models.CharField(max_length=40, unique=True, verbose_name='Session ID')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Currency')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('expires_at', models.DateTimeField(verbose_name='Expires at')),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('product_type', models.CharField(choices=[('tour', 'Tour'), ('event', 'Event'), ('transfer', 'Transfer')], max_length=20, verbose_name='Product type')),
                ('product_id', models.UUIDField(verbose_name='Product ID')),
                ('booking_date', models.DateField(verbose_name='Booking date')),
                ('booking_time', models.TimeField(verbose_name='Booking time')),
                ('variant_id', models.UUIDField(blank=True, null=True, verbose_name='Variant ID')),
                ('variant_name', models.CharField(blank=True, max_length=100, verbose_name='Variant name')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit price')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total price')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Currency')),
                ('selected_options', models.JSONField(default=list, verbose_name='Selected options')),
                ('options_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Options total')),
                ('booking_data', models.JSONField(default=dict, verbose_name='Booking data')),
                ('is_reserved', models.BooleanField(default=False, verbose_name='Is reserved')),
                ('reservation_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Reservation expires at')),
            ],
            options={
                'verbose_name': 'Cart Item',
                'verbose_name_plural': 'Cart Items',
                'ordering': ['created_at'],
            },
        ),
    ]
