# Generated by Django 5.0.2 on 2025-09-10 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_initial'),
        ('cart', '0003_cartitem_dropoff_date_and_more'),
    ]

    operations = [
    ]
