# Generated by Django 5.0.2 on 2025-09-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_merge_20250910_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='dropoff_location_custom',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Custom dropoff location'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='pickup_location_custom',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Custom pickup location'),
        ),
    ]
