# Generated by Django 5.0.2 on 2025-09-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_cartitem_dropoff_location_custom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='variant_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Variant ID'),
        ),
    ]
