# Interactive environment setup script
# Run this script to set up environment variables interactively

Write-Host "Setting up production environment variables..." -ForegroundColor Blue
Write-Host "This script will prompt for sensitive information. Make sure you're in a secure environment." -ForegroundColor Yellow

# Start with basic template
$envContent = @"
# Production Environment Variables for Peykan Tourism Platform
# Generated by setup-env.ps1

# Django Settings
DEBUG=False
SECRET_KEY=django-insecure-peykan-tourism-prod-2024
ALLOWED_HOSTS=peykantravelistanbul.com,www.peykantravelistanbul.com,localhost,127.0.0.1

# Database - PostgreSQL for production
DATABASE_URL=postgresql://peykan_user:peykan_password@postgres:5432/peykan

# Redis Cache
REDIS_URL=redis://redis:6379/1

# CORS - Production settings
CORS_ALLOWED_ORIGINS=https://peykantravelistanbul.com,https://www.peykantravelistanbul.com,http://localhost:3000

# Internationalization
LANGUAGES=fa,en,tr
DEFAULT_LANGUAGE=fa

# Currency
DEFAULT_CURRENCY=USD
SUPPORTED_CURRENCIES=USD,EUR,TRY,IRR

# Email Configuration
EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
EMAIL_HOST=smtp.gmail.com
EMAIL_PORT=587
EMAIL_USE_TLS=True
DEFAULT_FROM_EMAIL=noreply@peykantravelistanbul.com

# File Storage
MEDIA_URL=/media/
STATIC_URL=/static/
STATIC_ROOT=staticfiles/

# JWT Settings
JWT_SECRET_KEY=jwt-secret-key-change-this
JWT_ACCESS_TOKEN_LIFETIME=30
JWT_REFRESH_TOKEN_LIFETIME=1440

# Payment Gateway
PAYMENT_GATEWAY=stripe

# Security Settings - Production
SESSION_COOKIE_SECURE=True
CSRF_COOKIE_SECURE=True
SECURE_SSL_REDIRECT=True
SECURE_HSTS_SECONDS=31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS=True
SECURE_BROWSER_XSS_FILTER=True
SECURE_CONTENT_TYPE_NOSNIFF=True

"@

$envContent | Out-File -FilePath "backend\.env.production" -Encoding UTF8

# Prompt for sensitive values
Write-Host ""
$emailUser = Read-Host "Enter EMAIL_HOST_USER (e.g., your-email@gmail.com)"
$emailPass = Read-Host "Enter EMAIL_HOST_PASSWORD (for Gmail, use App Password)" -AsSecureString
$kavenegarKey = Read-Host "Enter KAVENEGAR_API_KEY" -AsSecureString
$paymentKey = Read-Host "Enter PAYMENT_SECRET_KEY (starts with sk_)" -AsSecureString

# Convert secure strings to plain text
$emailPassPlain = [Runtime.InteropServices.Marshal]::PtrToStringAuto([Runtime.InteropServices.Marshal]::SecureStringToBSTR($emailPass))
$kavenegarKeyPlain = [Runtime.InteropServices.Marshal]::PtrToStringAuto([Runtime.InteropServices.Marshal]::SecureStringToBSTR($kavenegarKey))
$paymentKeyPlain = [Runtime.InteropServices.Marshal]::PtrToStringAuto([Runtime.InteropServices.Marshal]::SecureStringToBSTR($paymentKey))

# Add the values to the file
Add-Content -Path "backend\.env.production" -Value "EMAIL_HOST_USER=$emailUser"
Add-Content -Path "backend\.env.production" -Value "EMAIL_HOST_PASSWORD=$emailPassPlain"
Add-Content -Path "backend\.env.production" -Value "KAVENEGAR_API_KEY=$kavenegarKeyPlain"
Add-Content -Path "backend\.env.production" -Value "PAYMENT_SECRET_KEY=$paymentKeyPlain"

Write-Host "Environment file created: backend\.env.production" -ForegroundColor Green
Write-Host "Please review the file and update SECRET_KEY and JWT_SECRET_KEY with secure values if needed." -ForegroundColor Yellow
