# Generated by Django 5.2.6 on 2025-09-25 16:20

import django.db.models.deletion
import parler.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car_rentals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='carrental',
            name='agent',
            field=models.ForeignKey(help_text='Agent who owns this car rental', on_delete=django.db.models.deletion.CASCADE, related_name='car_rentals', to=settings.AUTH_USER_MODEL, verbose_name='Agent'),
        ),
        migrations.AddField(
            model_name='carrentalavailability',
            name='car_rental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='car_rentals.carrental', verbose_name='Car rental'),
        ),
        migrations.AddField(
            model_name='carrentalbooking',
            name='availability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='car_rentals.carrentalavailability', verbose_name='Availability period'),
        ),
        migrations.AddField(
            model_name='carrentalbooking',
            name='car_rental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='car_rentals.carrental', verbose_name='Car rental'),
        ),
        migrations.AddField(
            model_name='carrentalbooking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_rental_bookings', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='carrental',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_rentals', to='car_rentals.carrentalcategory', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='carrentalcategorytranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='car_rentals.carrentalcategory'),
        ),
        migrations.AddField(
            model_name='carrentalimage',
            name='car_rental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='car_rentals.carrental', verbose_name='Car rental'),
        ),
        migrations.AddIndex(
            model_name='carrentallocation',
            index=models.Index(fields=['city', 'country'], name='car_rentals_city_6f05c6_idx'),
        ),
        migrations.AddIndex(
            model_name='carrentallocation',
            index=models.Index(fields=['location_type', 'is_active'], name='car_rentals_locatio_9d113d_idx'),
        ),
        migrations.AddField(
            model_name='carrentalbooking',
            name='dropoff_location_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dropoff_bookings', to='car_rentals.carrentallocation', verbose_name='Dropoff location'),
        ),
        migrations.AddField(
            model_name='carrentalbooking',
            name='pickup_location_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_bookings', to='car_rentals.carrentallocation', verbose_name='Pickup location'),
        ),
        migrations.AddField(
            model_name='carrental',
            name='default_dropoff_locations',
            field=models.ManyToManyField(blank=True, help_text='Predefined locations where this car can be dropped off', related_name='car_rentals_dropoff', to='car_rentals.carrentallocation', verbose_name='Default dropoff locations'),
        ),
        migrations.AddField(
            model_name='carrental',
            name='default_pickup_locations',
            field=models.ManyToManyField(blank=True, help_text='Predefined locations where this car can be picked up', related_name='car_rentals_pickup', to='car_rentals.carrentallocation', verbose_name='Default pickup locations'),
        ),
        migrations.AddField(
            model_name='carrentallocationtranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='car_rentals.carrentallocation'),
        ),
        migrations.AddField(
            model_name='carrentaloptiontranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='car_rentals.carrentaloption'),
        ),
        migrations.AddField(
            model_name='carrentaltranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='car_rentals.carrental'),
        ),
        migrations.AddIndex(
            model_name='carrentalavailability',
            index=models.Index(fields=['car_rental', 'start_date'], name='car_rentals_car_ren_0ec28b_idx'),
        ),
        migrations.AddIndex(
            model_name='carrentalavailability',
            index=models.Index(fields=['start_date', 'end_date'], name='car_rentals_start_d_0f0b15_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='carrentalcategorytranslation',
            unique_together={('language_code', 'master')},
        ),
        migrations.AddIndex(
            model_name='carrentalbooking',
            index=models.Index(fields=['car_rental', 'pickup_date'], name='car_rentals_car_ren_d686b3_idx'),
        ),
        migrations.AddIndex(
            model_name='carrentalbooking',
            index=models.Index(fields=['user', 'status'], name='car_rentals_user_id_a35f32_idx'),
        ),
        migrations.AddIndex(
            model_name='carrentalbooking',
            index=models.Index(fields=['booking_reference'], name='car_rentals_booking_bd6c40_idx'),
        ),
        migrations.AddIndex(
            model_name='carrental',
            index=models.Index(fields=['brand', 'model'], name='car_rentals_brand_16e421_idx'),
        ),
        migrations.AddIndex(
            model_name='carrental',
            index=models.Index(fields=['category', 'is_active'], name='car_rentals_categor_fa4a16_idx'),
        ),
        migrations.AddIndex(
            model_name='carrental',
            index=models.Index(fields=['agent', 'is_active'], name='car_rentals_agent_i_157836_idx'),
        ),
        migrations.AddIndex(
            model_name='carrental',
            index=models.Index(fields=['city', 'country'], name='car_rentals_city_95cf7a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='carrentallocationtranslation',
            unique_together={('language_code', 'master')},
        ),
        migrations.AlterUniqueTogether(
            name='carrentaloptiontranslation',
            unique_together={('language_code', 'master')},
        ),
        migrations.AlterUniqueTogether(
            name='carrentaltranslation',
            unique_together={('language_code', 'master')},
        ),
    ]
