# Generated by Django 5.0.2 on 2025-09-10 16:33

import django.core.validators
import django.db.models.deletion
import parler.fields
import parler.models
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rentals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrental',
            name='allow_custom_dropoff_location',
            field=models.BooleanField(default=True, help_text='Allow customers to choose custom dropoff location', verbose_name='Allow custom dropoff location'),
        ),
        migrations.AddField(
            model_name='carrental',
            name='allow_custom_pickup_location',
            field=models.BooleanField(default=True, help_text='Allow customers to choose custom pickup location', verbose_name='Allow custom pickup location'),
        ),
        migrations.AddField(
            model_name='carrentalbooking',
            name='dropoff_location_coordinates',
            field=models.JSONField(blank=True, default=dict, help_text='Latitude and longitude for custom dropoff location', verbose_name='Dropoff location coordinates'),
        ),
        migrations.AddField(
            model_name='carrentalbooking',
            name='dropoff_location_custom',
            field=models.CharField(blank=True, max_length=255, verbose_name='Custom dropoff location'),
        ),
        migrations.AddField(
            model_name='carrentalbooking',
            name='dropoff_location_type',
            field=models.CharField(choices=[('predefined', 'Predefined Location'), ('custom', 'Custom Location'), ('same_as_pickup', 'Same as Pickup')], default='same_as_pickup', max_length=20, verbose_name='Dropoff location type'),
        ),
        migrations.AddField(
            model_name='carrentalbooking',
            name='pickup_location_coordinates',
            field=models.JSONField(blank=True, default=dict, help_text='Latitude and longitude for custom pickup location', verbose_name='Pickup location coordinates'),
        ),
        migrations.AddField(
            model_name='carrentalbooking',
            name='pickup_location_custom',
            field=models.CharField(blank=True, max_length=255, verbose_name='Custom pickup location'),
        ),
        migrations.AddField(
            model_name='carrentalbooking',
            name='pickup_location_type',
            field=models.CharField(choices=[('predefined', 'Predefined Location'), ('custom', 'Custom Location')], default='predefined', max_length=20, verbose_name='Pickup location type'),
        ),
        migrations.AlterField(
            model_name='carrental',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Base price (USD)'),
        ),
        migrations.CreateModel(
            name='CarRentalLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('location_type', models.CharField(choices=[('airport', 'Airport'), ('hotel', 'Hotel'), ('station', 'Train/Bus Station'), ('city_center', 'City Center'), ('port', 'Port'), ('other', 'Other')], default='other', max_length=20, verbose_name='Location type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort order')),
                ('operating_hours_start', models.TimeField(blank=True, null=True, verbose_name='Operating hours start')),
                ('operating_hours_end', models.TimeField(blank=True, null=True, verbose_name='Operating hours end')),
            ],
            options={
                'verbose_name': 'Car Rental Location',
                'verbose_name_plural': 'Car Rental Locations',
                'ordering': ['sort_order', 'id'],
                'indexes': [models.Index(fields=['city', 'country'], name='car_rentals_city_6f05c6_idx'), models.Index(fields=['location_type', 'is_active'], name='car_rentals_locatio_9d113d_idx')],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='carrental',
            name='default_dropoff_locations',
            field=models.ManyToManyField(blank=True, help_text='Predefined locations where this car can be dropped off', related_name='car_rentals_dropoff', to='car_rentals.carrentallocation', verbose_name='Default dropoff locations'),
        ),
        migrations.AddField(
            model_name='carrental',
            name='default_pickup_locations',
            field=models.ManyToManyField(blank=True, help_text='Predefined locations where this car can be picked up', related_name='car_rentals_pickup', to='car_rentals.carrentallocation', verbose_name='Default pickup locations'),
        ),
        migrations.AddField(
            model_name='carrentalbooking',
            name='dropoff_location_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dropoff_bookings', to='car_rentals.carrentallocation', verbose_name='Dropoff location'),
        ),
        migrations.AddField(
            model_name='carrentalbooking',
            name='pickup_location_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_bookings', to='car_rentals.carrentallocation', verbose_name='Pickup location'),
        ),
        migrations.CreateModel(
            name='CarRentalLocationTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=255, verbose_name='Location name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('address', models.TextField(verbose_name='Address')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='car_rentals.carrentallocation')),
            ],
            options={
                'verbose_name': 'Car Rental Location Translation',
                'db_table': 'car_rentals_carrentallocation_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
