# Generated by Django 5.0.2 on 2025-09-10 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rentals', '0002_carrental_allow_custom_dropoff_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrental',
            name='allow_hourly_rental',
            field=models.BooleanField(default=True, help_text='Allow rentals for less than 24 hours', verbose_name='Allow hourly rental'),
        ),
        migrations.AddField(
            model_name='carrental',
            name='max_hourly_rental_hours',
            field=models.PositiveIntegerField(default=23, help_text='Maximum hours for hourly rental (before switching to daily)', verbose_name='Maximum hourly rental hours'),
        ),
        migrations.AddField(
            model_name='carrental',
            name='min_rent_hours',
            field=models.PositiveIntegerField(default=8, help_text='Minimum rental period in hours (for same-day rentals)', verbose_name='Minimum rental hours'),
        ),
    ]
