# Generated by Django 5.2.6 on 2025-09-25 16:20

import django.db.models.deletion
import parler.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tours', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewreport',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_reports', to=settings.AUTH_USER_MODEL, verbose_name='Moderated By'),
        ),
        migrations.AddField(
            model_name='reviewreport',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_reports', to=settings.AUTH_USER_MODEL, verbose_name='Reporter'),
        ),
        migrations.AddField(
            model_name='reviewresponse',
            name='responder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_responses', to=settings.AUTH_USER_MODEL, verbose_name='Responder'),
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='tours.tour', verbose_name='Tour'),
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_bookings', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='tourcancellationpolicy',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_policies', to='tours.tour', verbose_name='Tour'),
        ),
        migrations.AddField(
            model_name='tour',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='tours.tourcategory', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='tourcategorytranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='tours.tourcategory'),
        ),
        migrations.AddField(
            model_name='tourgallery',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='tours.tour', verbose_name='Tour'),
        ),
        migrations.AddField(
            model_name='touritinerary',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='tours.tour', verbose_name='Tour'),
        ),
        migrations.AddField(
            model_name='touritinerarytranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='tours.touritinerary'),
        ),
        migrations.AddField(
            model_name='touroption',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='tours.tour', verbose_name='Tour'),
        ),
        migrations.AddField(
            model_name='tourpricing',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='tours.tour', verbose_name='Tour'),
        ),
        migrations.AddField(
            model_name='tourreview',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_tour_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Moderated By'),
        ),
        migrations.AddField(
            model_name='tourreview',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tours.tour', verbose_name='Tour'),
        ),
        migrations.AddField(
            model_name='tourreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_reviews', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='reviewresponse',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='tours.tourreview', verbose_name='Review'),
        ),
        migrations.AddField(
            model_name='reviewreport',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='tours.tourreview', verbose_name='Review'),
        ),
        migrations.AddField(
            model_name='tourschedule',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='tours.tour', verbose_name='Tour'),
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='tours.tourschedule', verbose_name='Schedule'),
        ),
        migrations.AddField(
            model_name='tourschedulevariantcapacity',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_capacities', to='tours.tourschedule', verbose_name='Schedule'),
        ),
        migrations.AddField(
            model_name='tourtranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='tours.tour'),
        ),
        migrations.AddField(
            model_name='tourvariant',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='tours.tour', verbose_name='Tour'),
        ),
        migrations.AddField(
            model_name='tourschedulevariantcapacity',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_capacities', to='tours.tourvariant', verbose_name='Variant'),
        ),
        migrations.AddField(
            model_name='tourschedule',
            name='available_variants',
            field=models.ManyToManyField(blank=True, help_text='Variants available for this specific schedule. If empty, all tour variants are available.', related_name='schedules', to='tours.tourvariant', verbose_name='Available Variants'),
        ),
        migrations.AddField(
            model_name='tourpricing',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='tours.tourvariant', verbose_name='Variant'),
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='tours.tourvariant', verbose_name='Variant'),
        ),
        migrations.AlterUniqueTogether(
            name='tourcancellationpolicy',
            unique_together={('tour', 'hours_before')},
        ),
        migrations.AlterUniqueTogether(
            name='tourcategorytranslation',
            unique_together={('language_code', 'master')},
        ),
        migrations.AlterUniqueTogether(
            name='touritinerarytranslation',
            unique_together={('language_code', 'master')},
        ),
        migrations.AlterUniqueTogether(
            name='tourreview',
            unique_together={('tour', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='reviewresponse',
            unique_together={('review', 'responder')},
        ),
        migrations.AlterUniqueTogether(
            name='reviewreport',
            unique_together={('review', 'reporter')},
        ),
        migrations.AlterUniqueTogether(
            name='tourtranslation',
            unique_together={('language_code', 'master')},
        ),
        migrations.AlterUniqueTogether(
            name='tourvariant',
            unique_together={('tour', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='tourschedulevariantcapacity',
            unique_together={('schedule', 'variant')},
        ),
        migrations.AlterUniqueTogether(
            name='tourschedule',
            unique_together={('tour', 'start_date')},
        ),
        migrations.AlterUniqueTogether(
            name='tourpricing',
            unique_together={('tour', 'variant', 'age_group')},
        ),
    ]
