# Generated by Django 5.0.2 on 2025-06-26 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourcategory',
            name='city',
        ),
        migrations.RemoveField(
            model_name='tourcategory',
            name='country',
        ),
        migrations.RemoveField(
            model_name='tourcategory',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='tourcategory',
            name='image',
        ),
        migrations.RemoveField(
            model_name='tourcategory',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='tourcategory',
            name='is_popular',
        ),
        migrations.RemoveField(
            model_name='tourcategory',
            name='price',
        ),
    ]
