# Generated by Django 5.0.2 on 2025-07-05 18:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_remove_tourcategory_city_remove_tourcategory_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourpricing',
            name='base_price',
        ),
        migrations.RemoveField(
            model_name='tourpricing',
            name='discount_percentage',
        ),
        migrations.AddField(
            model_name='touroption',
            name='price_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Price percentage'),
        ),
        migrations.AddField(
            model_name='tourpricing',
            name='factor',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)], verbose_name='Price factor'),
        ),
        migrations.AddField(
            model_name='tourvariant',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Base price (USD)'),
        ),
        migrations.AlterField(
            model_name='touroption',
            name='max_quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Maximum quantity'),
        ),
    ]
