# Generated by Django 5.0.2 on 2025-07-05 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_remove_tourpricing_base_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourschedule',
            old_name='variant_capacities',
            new_name='variant_capacities_raw',
        ),
    ]
