# Generated by Django 5.0.2 on 2025-08-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_rename_variant_capacities_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourschedule',
            name='variant_capacities_raw',
        ),
        migrations.AddField(
            model_name='tourschedule',
            name='availability_note',
            field=models.CharField(blank=True, max_length=255, verbose_name='Availability Note'),
        ),
        migrations.AddField(
            model_name='tourschedule',
            name='availability_override',
            field=models.BooleanField(default=False, verbose_name='Override availability'),
        ),
        migrations.AddField(
            model_name='tourschedule',
            name='price_adjustment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Price Adjustment'),
        ),
        migrations.AddField(
            model_name='tourschedule',
            name='price_adjustment_type',
            field=models.CharField(choices=[('fixed', 'Fixed Amount'), ('percentage', 'Percentage')], default='fixed', max_length=10, verbose_name='Adjustment Type'),
        ),
    ]
