# Generated by Django 5.0.2 on 2025-08-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_remove_tourschedule_variant_capacities_raw_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourschedule',
            name='variant_capacities_raw',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Variant capacities'),
        ),
    ]
