# Generated by Django 5.0.2 on 2025-08-22 00:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_add_schedule_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tourreview',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('quality', 'Quality'), ('price', 'Price'), ('service', 'Service'), ('experience', 'Experience')], default='general', max_length=20, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='tourreview',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Moderated At'),
        ),
        migrations.AddField(
            model_name='tourreview',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_tour_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Moderated By'),
        ),
        migrations.AddField(
            model_name='tourreview',
            name='moderation_notes',
            field=models.TextField(blank=True, verbose_name='Moderation Notes'),
        ),
        migrations.AddField(
            model_name='tourreview',
            name='sentiment_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Sentiment Score'),
        ),
        migrations.AddField(
            model_name='tourreview',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Moderation'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('flagged', 'Flagged for Review')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
