# Generated by Django 5.0.2 on 2025-08-27 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0009_reviewreport_reviewresponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourschedule',
            name='current_capacity',
        ),
        migrations.RemoveField(
            model_name='tourschedule',
            name='max_capacity',
        ),
    ]
