# Generated by Django 5.0.2 on 2025-08-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0010_remove_tourschedule_current_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Image'),
        ),
    ]
