# Generated by Django 5.0.2 on 2025-09-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0012_tourcancellationpolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourschedule',
            name='total_confirmed_capacity',
            field=models.PositiveIntegerField(default=0, help_text='Total capacity confirmed in paid orders', verbose_name='Total Confirmed Capacity'),
        ),
        migrations.AddField(
            model_name='tourschedule',
            name='total_reserved_capacity',
            field=models.PositiveIntegerField(default=0, help_text='Total capacity currently reserved in carts and pending orders', verbose_name='Total Reserved Capacity'),
        ),
    ]
