# Generated by Django 5.0.2 on 2025-09-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0013_add_capacity_tracking_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourschedule',
            name='available_variants',
            field=models.ManyToManyField(blank=True, help_text='Variants available for this specific schedule. If empty, all tour variants are available.', related_name='schedules', to='tours.tourvariant', verbose_name='Available Variants'),
        ),
    ]
