# Generated by Django 5.0.2 on 2025-09-06 12:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0014_tourschedule_available_variants'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourGallery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('image', models.ImageField(upload_to='tours/gallery/', verbose_name='Image')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Image Title')),
                ('description', models.TextField(blank=True, verbose_name='Image Description')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='tours.tour', verbose_name='Tour')),
            ],
            options={
                'verbose_name': 'Tour Gallery Image',
                'verbose_name_plural': 'Tour Gallery Images',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
