# Generated by Django 5.0.2 on 2025-09-06 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0015_add_tour_gallery_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='gallery',
        ),
    ]
