# Generated by Django 5.0.2 on 2025-09-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0016_remove_gallery_json_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='is_seasonal',
            field=models.BooleanField(default=False, help_text='Mark as seasonal tour (summer/winter specials, holidays, etc.)', verbose_name='Is seasonal'),
        ),
        migrations.AddField(
            model_name='tour',
            name='is_special',
            field=models.BooleanField(default=False, help_text='Mark as special tour for premium display on homepage', verbose_name='Is special'),
        ),
    ]
