# Generated by Django 5.0.2 on 2025-09-15 20:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0018_alter_tour_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourschedule',
            name='variant_capacities_raw',
            field=models.JSONField(blank=True, default=dict, help_text='Legacy field - will be removed after migration to relational model', null=True, verbose_name='Variant capacities (Legacy)'),
        ),
        migrations.CreateModel(
            name='TourScheduleVariantCapacity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('total_capacity', models.PositiveIntegerField(help_text='Maximum capacity for this variant on this schedule', verbose_name='Total Capacity')),
                ('reserved_capacity', models.PositiveIntegerField(default=0, help_text='Capacity currently reserved in carts and pending orders', verbose_name='Reserved Capacity')),
                ('confirmed_capacity', models.PositiveIntegerField(default=0, help_text='Capacity confirmed in paid orders', verbose_name='Confirmed Capacity')),
                ('price_adjustment', models.DecimalField(decimal_places=2, default=0, help_text='Additional price adjustment for this variant on this schedule', max_digits=10, verbose_name='Price Adjustment')),
                ('price_adjustment_type', models.CharField(choices=[('fixed', 'Fixed Amount'), ('percentage', 'Percentage')], default='fixed', max_length=10, verbose_name='Adjustment Type')),
                ('is_available', models.BooleanField(default=True, help_text='Whether this variant is available for this schedule', verbose_name='Available')),
                ('availability_note', models.CharField(blank=True, help_text='Optional note about availability (e.g., "Few seats left")', max_length=255, verbose_name='Availability Note')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_capacities', to='tours.tourschedule', verbose_name='Schedule')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_capacities', to='tours.tourvariant', verbose_name='Variant')),
            ],
            options={
                'verbose_name': 'Schedule Variant Capacity',
                'verbose_name_plural': 'Schedule Variant Capacities',
                'ordering': ['schedule', 'variant__name'],
                'unique_together': {('schedule', 'variant')},
            },
        ),
    ]
