# Generated by Django 5.2.6 on 2025-09-25 16:20

import django.db.models.deletion
import parler.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transfers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transferbooking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_bookings', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddIndex(
            model_name='transferlocation',
            index=models.Index(fields=['city', 'country'], name='transfers_t_city_445242_idx'),
        ),
        migrations.AddIndex(
            model_name='transferlocation',
            index=models.Index(fields=['location_type'], name='transfers_t_locatio_f397ba_idx'),
        ),
        migrations.AddIndex(
            model_name='transferlocation',
            index=models.Index(fields=['is_active', 'is_popular'], name='transfers_t_is_acti_078ab9_idx'),
        ),
        migrations.AddIndex(
            model_name='transferlocation',
            index=models.Index(fields=['latitude', 'longitude'], name='transfers_t_latitud_b9687e_idx'),
        ),
        migrations.AddField(
            model_name='transferlocationtranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='transfers.transferlocation'),
        ),
        migrations.AddField(
            model_name='transferoptiontranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='transfers.transferoption'),
        ),
        migrations.AddField(
            model_name='transferroute',
            name='destination_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_routes', to='transfers.transferlocation', verbose_name='Destination Location'),
        ),
        migrations.AddField(
            model_name='transferroute',
            name='origin_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_routes', to='transfers.transferlocation', verbose_name='Origin Location'),
        ),
        migrations.AddField(
            model_name='transferoption',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='transfers.transferroute', verbose_name='Route'),
        ),
        migrations.AddField(
            model_name='transfercancellationpolicy',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_policies', to='transfers.transferroute', verbose_name='Route'),
        ),
        migrations.AddField(
            model_name='transferbooking',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='transfers.transferroute', verbose_name='Route'),
        ),
        migrations.AddField(
            model_name='transferroutepricing',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='transfers.transferroute', verbose_name='Route'),
        ),
        migrations.AddField(
            model_name='transferbooking',
            name='pricing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='transfers.transferroutepricing', verbose_name='Pricing'),
        ),
        migrations.AddField(
            model_name='transferroutetranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='transfers.transferroute'),
        ),
        migrations.AlterUniqueTogether(
            name='transferlocationtranslation',
            unique_together={('language_code', 'master')},
        ),
        migrations.AlterUniqueTogether(
            name='transferoptiontranslation',
            unique_together={('language_code', 'master')},
        ),
        migrations.AddIndex(
            model_name='transferroute',
            index=models.Index(fields=['origin', 'destination'], name='transfers_t_origin_5a222e_idx'),
        ),
        migrations.AddIndex(
            model_name='transferroute',
            index=models.Index(fields=['is_active'], name='transfers_t_is_acti_38aee7_idx'),
        ),
        migrations.AddIndex(
            model_name='transferroute',
            index=models.Index(fields=['slug'], name='transfers_t_slug_9797ac_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='transferroute',
            unique_together={('origin', 'destination')},
        ),
        migrations.AddIndex(
            model_name='transferoption',
            index=models.Index(fields=['option_type'], name='transfers_t_option__b53fcf_idx'),
        ),
        migrations.AddIndex(
            model_name='transferoption',
            index=models.Index(fields=['is_active'], name='transfers_t_is_acti_2cec5b_idx'),
        ),
        migrations.AddIndex(
            model_name='transferoption',
            index=models.Index(fields=['route'], name='transfers_t_route_i_200305_idx'),
        ),
        migrations.AddIndex(
            model_name='transferoption',
            index=models.Index(fields=['vehicle_type'], name='transfers_t_vehicle_5884bd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='transfercancellationpolicy',
            unique_together={('route', 'hours_before')},
        ),
        migrations.AddIndex(
            model_name='transferroutepricing',
            index=models.Index(fields=['route', 'vehicle_type'], name='transfers_t_route_i_64239c_idx'),
        ),
        migrations.AddIndex(
            model_name='transferroutepricing',
            index=models.Index(fields=['is_active'], name='transfers_t_is_acti_a03bbb_idx'),
        ),
        migrations.AddConstraint(
            model_name='transferroutepricing',
            constraint=models.UniqueConstraint(fields=('route', 'vehicle_type'), name='unique_route_vehicle'),
        ),
        migrations.AlterUniqueTogether(
            name='transferroutepricing',
            unique_together={('route', 'vehicle_type')},
        ),
        migrations.AddIndex(
            model_name='transferbooking',
            index=models.Index(fields=['booking_reference'], name='transfers_t_booking_b916fb_idx'),
        ),
        migrations.AddIndex(
            model_name='transferbooking',
            index=models.Index(fields=['user', 'created_at'], name='transfers_t_user_id_f4d043_idx'),
        ),
        migrations.AddIndex(
            model_name='transferbooking',
            index=models.Index(fields=['route', 'outbound_date'], name='transfers_t_route_i_a14785_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='transferroutetranslation',
            unique_together={('language_code', 'master')},
        ),
    ]
