# Generated by Django 5.0.2 on 2025-07-08 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferroutepricing',
            name='pricing_metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Pricing metadata'),
        ),
    ]
