# Generated by Django 5.0.2 on 2025-08-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0002_transferroutepricing_pricing_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferroutepricing',
            name='currency',
            field=models.CharField(default='USD', max_length=3, verbose_name='Currency'),
        ),
    ]
