# Generated by Django 5.0.2 on 2025-08-20 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0002_add_cancellation_policy'),
        ('transfers', '0003_transferroutepricing_currency'),
    ]

    operations = [
    ]
