# Generated by Django 5.0.2 on 2025-08-23 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0004_merge_20250820_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferoption',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='transfers.transferroute', verbose_name='Route'),
        ),
        migrations.AddField(
            model_name='transferoption',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('van', 'Van'), ('sprinter', 'Sprinter'), ('bus', 'Bus'), ('limousine', 'Limousine')], max_length=20, null=True, verbose_name='Vehicle type'),
        ),
        migrations.AddIndex(
            model_name='transferoption',
            index=models.Index(fields=['route'], name='transfers_t_route_i_200305_idx'),
        ),
        migrations.AddIndex(
            model_name='transferoption',
            index=models.Index(fields=['vehicle_type'], name='transfers_t_vehicle_5884bd_idx'),
        ),
    ]
