# Generated by Django 5.0.2 on 2025-08-23 20:45

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0005_transferoption_route_transferoption_vehicle_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferCancellationPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('hours_before', models.PositiveIntegerField(help_text='Number of hours before departure when this policy applies', verbose_name='Hours before departure')),
                ('refund_percentage', models.PositiveIntegerField(help_text='Percentage of refund for cancellations within this time frame', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Refund percentage')),
                ('description', models.TextField(blank=True, help_text='Human-readable description of this policy', verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_policies', to='transfers.transferroute', verbose_name='Route')),
            ],
            options={
                'verbose_name': 'Transfer Cancellation Policy',
                'verbose_name_plural': 'Transfer Cancellation Policies',
                'ordering': ['-hours_before'],
                'unique_together': {('route', 'hours_before')},
            },
        ),
    ]
