# Generated by Django 5.0.2 on 2025-08-23 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0006_add_cancellation_policy_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferroute',
            name='estimated_duration_minutes',
            field=models.PositiveIntegerField(default=45, help_text='Estimated travel time in minutes', verbose_name='Estimated duration (minutes)'),
        ),
    ]
