# Generated by Django 5.0.2 on 2025-09-12 16:40

import django.db.models.deletion
import parler.fields
import parler.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0007_add_estimated_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('address', models.TextField(verbose_name='Address')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitude')),
                ('location_type', models.CharField(choices=[('airport', 'Airport'), ('hotel', 'Hotel'), ('station', 'Station'), ('landmark', 'Landmark'), ('custom', 'Custom Location')], default='custom', max_length=20, verbose_name='Location type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Is popular')),
            ],
            options={
                'verbose_name': 'Transfer Location',
                'verbose_name_plural': 'Transfer Locations',
                'indexes': [models.Index(fields=['city', 'country'], name='transfers_t_city_445242_idx'), models.Index(fields=['location_type'], name='transfers_t_locatio_f397ba_idx'), models.Index(fields=['is_active', 'is_popular'], name='transfers_t_is_acti_078ab9_idx'), models.Index(fields=['latitude', 'longitude'], name='transfers_t_latitud_b9687e_idx')],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='transferroute',
            name='destination_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_routes', to='transfers.transferlocation', verbose_name='Destination Location'),
        ),
        migrations.AddField(
            model_name='transferroute',
            name='origin_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_routes', to='transfers.transferlocation', verbose_name='Origin Location'),
        ),
        migrations.CreateModel(
            name='TransferLocationTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='transfers.transferlocation')),
            ],
            options={
                'verbose_name': 'Transfer Location Translation',
                'db_table': 'transfers_transferlocation_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
