# Generated by Django 5.0.2 on 2025-06-27 22:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('password_change', 'Password Change'), ('email_verification', 'Email Verification'), ('phone_verification', 'Phone Verification'), ('profile_update', 'Profile Update'), ('password_reset_request', 'Password Reset Request'), ('password_reset_complete', 'Password Reset Complete')], max_length=30, verbose_name='Activity Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'User Activity',
                'verbose_name_plural': 'User Activities',
                'db_table': 'user_activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='otpcode',
            options={'verbose_name': 'OTP Code', 'verbose_name_plural': 'OTP Codes'},
        ),
        migrations.RemoveField(
            model_name='otpcode',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='otpcode',
            name='is_expired',
        ),
        migrations.RemoveField(
            model_name='otpcode',
            name='target',
        ),
        migrations.RemoveField(
            model_name='otpcode',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='otpcode',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='otpcode',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='otpcode',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Used At'),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='expires_at',
            field=models.DateTimeField(verbose_name='Expires At'),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='Is Used'),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='otp_type',
            field=models.CharField(choices=[('email_verification', 'Email Verification'), ('phone_verification', 'Phone Verification'), ('password_reset', 'Password Reset'), ('login', 'Login')], max_length=20, verbose_name='OTP Type'),
        ),
        migrations.AddIndex(
            model_name='otpcode',
            index=models.Index(fields=['user', 'otp_type'], name='user_otps_user_id_71cb0f_idx'),
        ),
        migrations.AddIndex(
            model_name='otpcode',
            index=models.Index(fields=['email', 'otp_type'], name='user_otps_email_c268bf_idx'),
        ),
        migrations.AddIndex(
            model_name='otpcode',
            index=models.Index(fields=['phone', 'otp_type'], name='user_otps_phone_92a3d3_idx'),
        ),
        migrations.AddIndex(
            model_name='otpcode',
            index=models.Index(fields=['expires_at'], name='user_otps_expires_5a164f_idx'),
        ),
        migrations.AlterModelTable(
            name='otpcode',
            table='user_otps',
        ),
        migrations.AddField(
            model_name='useractivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['user', 'activity_type'], name='user_activi_user_id_290628_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['created_at'], name='user_activi_created_9fa3ca_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['ip_address'], name='user_activi_ip_addr_ebdeb1_idx'),
        ),
    ]
