# Generated by Django 5.0.2 on 2025-09-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_userprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='preferred_language',
            field=models.CharField(default='fa', max_length=10, verbose_name='Preferred Language'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(default='Asia/Tehran', max_length=50, verbose_name='Timezone'),
        ),
    ]
