# Generated by Django 5.0.2 on 2025-09-03 09:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('cart_max_items_guest', models.PositiveIntegerField(default=5, verbose_name='Guest cart max items')),
                ('cart_max_total_guest', models.DecimalField(decimal_places=2, default=1000.0, max_digits=10, verbose_name='Guest cart max total (USD)')),
                ('cart_max_carts_guest', models.PositiveIntegerField(default=20, verbose_name='Guest max carts')),
                ('cart_rate_limit_guest', models.PositiveIntegerField(default=30, verbose_name='Guest rate limit (requests/minute)')),
                ('cart_rate_limit_user', models.PositiveIntegerField(default=20, verbose_name='User rate limit (requests/minute)')),
                ('order_max_pending_per_user', models.PositiveIntegerField(default=3, verbose_name='Max pending orders per user')),
                ('order_max_pending_per_product', models.PositiveIntegerField(default=1, verbose_name='Max pending orders per product')),
                ('capacity_check_enabled', models.BooleanField(default=True, verbose_name='Enable capacity checks')),
                ('capacity_reservation_duration', models.PositiveIntegerField(default=30, verbose_name='Capacity reservation duration (minutes)')),
                ('guest_infant_max', models.PositiveIntegerField(default=2, verbose_name='Max infants per booking')),
                ('guest_booking_timeout', models.PositiveIntegerField(default=15, verbose_name='Guest booking timeout (minutes)')),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
