# Generated by Django 5.0.2 on 2025-09-06 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='cart_max_items_user',
            field=models.PositiveIntegerField(default=10, verbose_name='User cart max items'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='cart_max_total_user',
            field=models.DecimalField(decimal_places=2, default=5000.0, max_digits=10, verbose_name='User cart max total (USD)'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='cart_max_items_guest',
            field=models.PositiveIntegerField(default=3, verbose_name='Guest cart max items'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='cart_max_total_guest',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10, verbose_name='Guest cart max total (USD)'),
        ),
    ]
